# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert-rules/*.yaml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
        labels:
          name: prometheus
  ##Static discovery of nodes in prometheus        
  # - job_name: "nodes"
  #   static_configs:
  #     - targets: ["node-1.lingaiah.online:9100"]
  #       labels:
  #         name: node-1
  #     - targets: ["node-2.lingaiah.online:9100"]
  #       labels:
  #         name: node-2

  ##Dynamic discovery of nodes in prometheus 
  # - job_name: 'ec2-nodes'
  #   ec2_sd_configs:
  #     - region: us-east-1
  #       port: 9100
  #   relabel_configs:
  #     - source_labels: [__meta_ec2_instance_id]
  #       target_label: instance_id
  #     - source_labels: [__meta_ec2_private_ip]
  #       target_label: private_ip
  #     - source_labels: [__meta_ec2_tag_Name]
  #       target_label: instance_name
  #       regex: node-.*
  #       action: keep

  - job_name: 'ec2-nodes'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:                 # optional EC2 filters
          - name: "tag:Environment"
            values: ["dev"]
    
    relabel_configs:
      # Keep only instances whose Name tag matches "node-*"
      - source_labels: [__meta_ec2_tag_Name]
        regex: node-.*
        action: keep

      # Set label "name" from EC2 tag Name
      - source_labels: [__meta_ec2_tag_Name]
        target_label: name

      # Set the target label for instance ID
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id

      # Set the target label for private IP
      - source_labels: [__meta_ec2_private_ip]
        target_label: private_ip

       # Set the actual address (IP:port) Prometheus scrapes
      - source_labels: [__meta_ec2_private_ip]
        target_label: __address__
        replacement: "$1:9100"

         
  - job_name: "ec2_sd"
    ec2_sd_configs:
    - region: us-east-1
      port: 9100
      filters:
        - name: tag:Monitoring
          values:
            - true
    relabel_configs:
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      - source_labels: [__meta_ec2_private_ip]
        target_label: private_ip
      - source_labels: [__meta_ec2_tag_Name]
        target_label: name
        
