groups:
- name: Disk-Utilization-High
  rules:
  - alert: Disk-Utilization-High Alert
    expr: 100 - (node_filesystem_avail_bytes{mountpoint="/"}*100/node_filesystem_size_bytes{mountpoint="/"})
    for: 1m
    labels:
      severity: 'critical'
    annotations:
      summary: Disk-Utilization-High
